# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photos_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='photos',
            name='capture_date',
            field=models.DateTimeField(verbose_name='Capture Date'),
        ),
    ]
