# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20171112_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='capture_date',
            field=models.DateField(verbose_name='Capture Date'),
        ),
    ]
