# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='url',
            field=models.CharField(default='null', max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
