# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0010_auto_20171115_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='sales_embed',
            field=models.TextField(null=True),
        ),
    ]
